package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatalogoPlatoPlatosId generated by hbm2java
 */
@Embeddable
public class CatalogoPlatoPlatosId implements java.io.Serializable {

	private String catalogoPlatoCatalogoid;
	private long catalogoPlatoPlatoId;
	private long platosId;

	public CatalogoPlatoPlatosId() {
	}

	public CatalogoPlatoPlatosId(String catalogoPlatoCatalogoid, long catalogoPlatoPlatoId, long platosId) {
		this.catalogoPlatoCatalogoid = catalogoPlatoCatalogoid;
		this.catalogoPlatoPlatoId = catalogoPlatoPlatoId;
		this.platosId = platosId;
	}

	@Column(name = "catalogo_plato_catalogoid", nullable = false)
	public String getCatalogoPlatoCatalogoid() {
		return this.catalogoPlatoCatalogoid;
	}

	public void setCatalogoPlatoCatalogoid(String catalogoPlatoCatalogoid) {
		this.catalogoPlatoCatalogoid = catalogoPlatoCatalogoid;
	}

	@Column(name = "catalogo_plato_plato_id", nullable = false)
	public long getCatalogoPlatoPlatoId() {
		return this.catalogoPlatoPlatoId;
	}

	public void setCatalogoPlatoPlatoId(long catalogoPlatoPlatoId) {
		this.catalogoPlatoPlatoId = catalogoPlatoPlatoId;
	}

	@Column(name = "platos_id", unique = true, nullable = false)
	public long getPlatosId() {
		return this.platosId;
	}

	public void setPlatosId(long platosId) {
		this.platosId = platosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatalogoPlatoPlatosId))
			return false;
		CatalogoPlatoPlatosId castOther = (CatalogoPlatoPlatosId) other;

		return ((this.getCatalogoPlatoCatalogoid() == castOther.getCatalogoPlatoCatalogoid())
				|| (this.getCatalogoPlatoCatalogoid() != null && castOther.getCatalogoPlatoCatalogoid() != null
						&& this.getCatalogoPlatoCatalogoid().equals(castOther.getCatalogoPlatoCatalogoid())))
				&& (this.getCatalogoPlatoPlatoId() == castOther.getCatalogoPlatoPlatoId())
				&& (this.getPlatosId() == castOther.getPlatosId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCatalogoPlatoCatalogoid() == null ? 0 : this.getCatalogoPlatoCatalogoid().hashCode());
		result = 37 * result + (int) this.getCatalogoPlatoPlatoId();
		result = 37 * result + (int) this.getPlatosId();
		return result;
	}

}
