package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Catalogo generated by hbm2java
 */
@Entity
@Table(name = "catalogo", catalog = "scanappetite")
public class Catalogo implements java.io.Serializable {

	private String id;
	private Restaurante restaurante;
	private String descripcion;
	private Date horarioInicio;
	private Date horarioFin;
	private Set platos = new HashSet(0);

	public Catalogo() {
	}

	public Catalogo(String id, Restaurante restaurante) {
		this.id = id;
		this.restaurante = restaurante;
	}

	public Catalogo(String id, Restaurante restaurante, String descripcion, Date horarioInicio, Date horarioFin,
			Set platos) {
		this.id = id;
		this.restaurante = restaurante;
		this.descripcion = descripcion;
		this.horarioInicio = horarioInicio;
		this.horarioFin = horarioFin;
		this.platos = platos;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RestauranteID", nullable = false)
	public Restaurante getRestaurante() {
		return this.restaurante;
	}

	public void setRestaurante(Restaurante restaurante) {
		this.restaurante = restaurante;
	}

	@Column(name = "Descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario_inicio", length = 15)
	public Date getHorarioInicio() {
		return this.horarioInicio;
	}

	public void setHorarioInicio(Date horarioInicio) {
		this.horarioInicio = horarioInicio;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "horario_fin", length = 15)
	public Date getHorarioFin() {
		return this.horarioFin;
	}

	public void setHorarioFin(Date horarioFin) {
		this.horarioFin = horarioFin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "catalogo")
	public Set getPlatos() {
		return this.platos;
	}

	public void setPlatos(Set platos) {
		this.platos = platos;
	}

}
