package prueba;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CestaPlato generated by hbm2java
 */
@Entity
@Table(name = "cesta_plato", catalog = "scanappetite")
public class CestaPlato implements java.io.Serializable {

	private CestaPlatoId id;
	private Cesta cesta;

	public CestaPlato() {
	}

	public CestaPlato(CestaPlatoId id, Cesta cesta) {
		this.id = id;
		this.cesta = cesta;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "platoId", column = @Column(name = "PlatoID", nullable = false)),
			@AttributeOverride(name = "cestaId", column = @Column(name = "CestaId", nullable = false)) })
	public CestaPlatoId getId() {
		return this.id;
	}

	public void setId(CestaPlatoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CestaId", nullable = false, insertable = false, updatable = false)
	public Cesta getCesta() {
		return this.cesta;
	}

	public void setCesta(Cesta cesta) {
		this.cesta = cesta;
	}

}
