package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cesta generated by hbm2java
 */
@Entity
@Table(name = "cesta", catalog = "scanappetite")
public class Cesta implements java.io.Serializable {

	private int id;
	private String mesaId;
	private Set cestaPlatos = new HashSet(0);

	public Cesta() {
	}

	public Cesta(int id, String mesaId) {
		this.id = id;
		this.mesaId = mesaId;
	}

	public Cesta(int id, String mesaId, Set cestaPlatos) {
		this.id = id;
		this.mesaId = mesaId;
		this.cestaPlatos = cestaPlatos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MesaID", nullable = false)
	public String getMesaId() {
		return this.mesaId;
	}

	public void setMesaId(String mesaId) {
		this.mesaId = mesaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cesta")
	public Set getCestaPlatos() {
		return this.cestaPlatos;
	}

	public void setCestaPlatos(Set cestaPlatos) {
		this.cestaPlatos = cestaPlatos;
	}

}
