package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dishes generated by hbm2java
 */
@Entity
@Table(name = "dishes", catalog = "restaurant")
public class Dishes implements java.io.Serializable {

	private Long id;
	private Categories categories;
	private String nameEn;
	private String nameUa;
	private BigDecimal price;
	private Date time;
	private Set basketses = new HashSet(0);

	public Dishes() {
	}

	public Dishes(BigDecimal price) {
		this.price = price;
	}

	public Dishes(Categories categories, String nameEn, String nameUa, BigDecimal price, Date time, Set basketses) {
		this.categories = categories;
		this.nameEn = nameEn;
		this.nameUa = nameUa;
		this.price = price;
		this.time = time;
		this.basketses = basketses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@Column(name = "name_en")
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "name_ua")
	public String getNameUa() {
		return this.nameUa;
	}

	public void setNameUa(String nameUa) {
		this.nameUa = nameUa;
	}

	@Column(name = "price", nullable = false)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dishes")
	public Set getBasketses() {
		return this.basketses;
	}

	public void setBasketses(Set basketses) {
		this.basketses = basketses;
	}

}
