package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "restaurant", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Login implements java.io.Serializable {

	private long id;
	private String email;
	private String login;
	private String password;
	private String role;
	private Date time;
	private Set basketses = new HashSet(0);
	private Set orderses = new HashSet(0);

	public Login() {
	}

	public Login(long id, String email, String login) {
		this.id = id;
		this.email = email;
		this.login = login;
	}

	public Login(long id, String email, String login, String password, String role, Date time, Set basketses,
			Set orderses) {
		this.id = id;
		this.email = email;
		this.login = login;
		this.password = password;
		this.role = role;
		this.time = time;
		this.basketses = basketses;
		this.orderses = orderses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "login", unique = true, nullable = false)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "role")
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "login")
	public Set getBasketses() {
		return this.basketses;
	}

	public void setBasketses(Set basketses) {
		this.basketses = basketses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "login")
	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

}
