package prueba;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mesa generated by hbm2java
 */
@Entity
@Table(name = "mesa", catalog = "scanappetite")
public class Mesa implements java.io.Serializable {

	private String id;
	private Restaurante restaurante;
	private String ubicacion;
	private String estado;
	private Set restaurantes = new HashSet(0);
	private Set pedidos = new HashSet(0);

	public Mesa() {
	}

	public Mesa(String id, Restaurante restaurante) {
		this.id = id;
		this.restaurante = restaurante;
	}

	public Mesa(String id, Restaurante restaurante, String ubicacion, String estado, Set restaurantes, Set pedidos) {
		this.id = id;
		this.restaurante = restaurante;
		this.ubicacion = ubicacion;
		this.estado = estado;
		this.restaurantes = restaurantes;
		this.pedidos = pedidos;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RestauranteID", nullable = false)
	public Restaurante getRestaurante() {
		return this.restaurante;
	}

	public void setRestaurante(Restaurante restaurante) {
		this.restaurante = restaurante;
	}

	@Column(name = "Ubicacion")
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "Estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
	public Set getRestaurantes() {
		return this.restaurantes;
	}

	public void setRestaurantes(Set restaurantes) {
		this.restaurantes = restaurantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

}
