package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Plato generated by hbm2java
 */
@Entity
@Table(name = "plato", catalog = "scanappetite")
public class Plato implements java.io.Serializable {

	private Long id;
	private Catalogo catalogo;
	private String name;
	private BigDecimal price;
	private Date time;
	private Set cestaPlatos = new HashSet(0);

	public Plato() {
	}

	public Plato(Catalogo catalogo, String name) {
		this.catalogo = catalogo;
		this.name = name;
	}

	public Plato(Catalogo catalogo, String name, BigDecimal price, Date time, Set cestaPlatos) {
		this.catalogo = catalogo;
		this.name = name;
		this.price = price;
		this.time = time;
		this.cestaPlatos = cestaPlatos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "catalogo_id", nullable = false)
	public Catalogo getCatalogo() {
		return this.catalogo;
	}

	public void setCatalogo(Catalogo catalogo) {
		this.catalogo = catalogo;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", precision = 38)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 26)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plato")
	public Set getCestaPlatos() {
		return this.cestaPlatos;
	}

	public void setCestaPlatos(Set cestaPlatos) {
		this.cestaPlatos = cestaPlatos;
	}

}
