package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Restaurante generated by hbm2java
 */
@Entity
@Table(name = "restaurante", catalog = "scanappetite")
public class Restaurante implements java.io.Serializable {

	private String id;
	private Mesa mesa;
	private String direccion;
	private String denominacion;
	private String title;
	private Date horaApertura;
	private Date horaCierre;
	private Set catalogos = new HashSet(0);
	private Set mesas = new HashSet(0);

	public Restaurante() {
	}

	public Restaurante(String id) {
		this.id = id;
	}

	public Restaurante(String id, Mesa mesa, String direccion, String denominacion, String title, Date horaApertura,
			Date horaCierre, Set catalogos, Set mesas) {
		this.id = id;
		this.mesa = mesa;
		this.direccion = direccion;
		this.denominacion = denominacion;
		this.title = title;
		this.horaApertura = horaApertura;
		this.horaCierre = horaCierre;
		this.catalogos = catalogos;
		this.mesas = mesas;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MesaID")
	public Mesa getMesa() {
		return this.mesa;
	}

	public void setMesa(Mesa mesa) {
		this.mesa = mesa;
	}

	@Column(name = "Direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "Denominacion", length = 120)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_apertura", length = 15)
	public Date getHoraApertura() {
		return this.horaApertura;
	}

	public void setHoraApertura(Date horaApertura) {
		this.horaApertura = horaApertura;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_cierre", length = 15)
	public Date getHoraCierre() {
		return this.horaCierre;
	}

	public void setHoraCierre(Date horaCierre) {
		this.horaCierre = horaCierre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurante")
	public Set getCatalogos() {
		return this.catalogos;
	}

	public void setCatalogos(Set catalogos) {
		this.catalogos = catalogos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurante")
	public Set getMesas() {
		return this.mesas;
	}

	public void setMesas(Set mesas) {
		this.mesas = mesas;
	}

}
