package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequences generated by hbm2java
 */
@Entity
@Table(name = "sequences", catalog = "restaurant")
public class Sequences implements java.io.Serializable {

	private String name;
	private long nextVal;

	public Sequences() {
	}

	public Sequences(String name, long nextVal) {
		this.name = name;
		this.nextVal = nextVal;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "next_val", nullable = false)
	public long getNextVal() {
		return this.nextVal;
	}

	public void setNextVal(long nextVal) {
		this.nextVal = nextVal;
	}

}
