package prueba;
// Generated 18 dic 2023 23:11:31 by Hibernate Tools 4.3.6.Final


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import prueba.X.schemaTablesWithFullTableScansId;

/**
 * X.schemaTablesWithFullTableScans generated by hbm2java
 */
@Entity
@Table(name="x$schema_tables_with_full_table_scans"
    ,catalog="sys"
)
public class X.schemaTablesWithFullTableScans  implements java.io.Serializable {


     private X.schemaTablesWithFullTableScansId id;

    public X.schemaTablesWithFullTableScans() {
    }

    public X.schemaTablesWithFullTableScans(X.schemaTablesWithFullTableScansId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="objectSchema", column=@Column(name="object_schema", length=64) ), 
        @AttributeOverride(name="objectName", column=@Column(name="object_name", length=64) ), 
        @AttributeOverride(name="rowsFullScanned", column=@Column(name="rows_full_scanned", nullable=false) ), 
        @AttributeOverride(name="latency", column=@Column(name="latency", nullable=false) ) } )
    public X.schemaTablesWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTablesWithFullTableScansId id) {
        this.id = id;
    }




}


