logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework: DEBUG
    com:
      example: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ScanAppetite
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      logging:
        level:
         '[org.springframework]': DEBUG
         '[org.hibernate.SQL]': DEBUG
         '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
boot:
  admin:
    ui:
      show-details: always


