package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * CatalogoPlatoPlatos generated by hbm2java
 */
@Entity
@Table(name = "catalogo_plato_platos", catalog = "scanappetite", uniqueConstraints = @UniqueConstraint(columnNames = "platos_id"))
public class CatalogoPlatoPlatos implements java.io.Serializable {

	private CatalogoPlatoPlatosId id;

	public CatalogoPlatoPlatos() {
	}

	public CatalogoPlatoPlatos(CatalogoPlatoPlatosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "catalogoPlatoCatalogoid", column = @Column(name = "catalogo_plato_catalogoid", nullable = false)),
			@AttributeOverride(name = "catalogoPlatoPlatoId", column = @Column(name = "catalogo_plato_plato_id", nullable = false)),
			@AttributeOverride(name = "platosId", column = @Column(name = "platos_id", unique = true, nullable = false)) })
	public CatalogoPlatoPlatosId getId() {
		return this.id;
	}

	public void setId(CatalogoPlatoPlatosId id) {
		this.id = id;
	}

}
