package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final


import java.util.List;
import java.util.Set;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Cesta generated by hbm2java
 */
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
@Entity
@Table(name = "cesta", catalog = "scanappetite")
public class Cesta implements java.io.Serializable {
	
	private int id;

	//private List<Plato> platos;
	private String mesaId;

	private List<CestaPlato> cestaPlatos;

	// public List<Plato> getPlatos() {
	// return platos;
	// }

	

	public Cesta(String mesaId) {
		//this.id = id;
		this.mesaId = mesaId;
	}

	
	@Id
	@GeneratedValue
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/*
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PlatoId")
	public List<Plato> getPlatos() {
		return this.platos;
	}

	public void setPlato(List<Plato> plato) {
		this.platos = plato;
	}
	*/

	@Column(name = "MesaID", nullable = false)
	public String getMesaId() {
		return this.mesaId;
	}

	public void setMesaId(String mesaId) {
		this.mesaId = mesaId;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cesta")
	public List<CestaPlato> getCestaPlatos() {
		return this.cestaPlatos;
	}

	public void setCestaPlatos(List<CestaPlato> cestaPlatos) {
		this.cestaPlatos = cestaPlatos;
	}

}
