package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Id;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString

/**
 * CestaPlato generated by hbm2java
 */
@Entity
@Table(name = "cesta_plato", catalog = "scanappetite")
public class CestaPlato implements java.io.Serializable {

	private int id;
	private Cesta cesta;
	private Plato plato;
	@Column(name = "selected")
	private boolean selected;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CestaId", nullable = false)
	public Cesta getCesta() {
		return this.cesta;
	}

	public void setCesta(Cesta cesta) {
		this.cesta = cesta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PlatoID", nullable = false)
	public Plato getPlato() {
		return this.plato;
	}

	public void setPlato(Plato plato) {
		this.plato = plato;
	}

	public boolean isSelected() {
		return selected;
	}

	public void setSelected(boolean selected) {
		this.selected = selected;
	}
	
	
}
