package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * DetallesPago generated by hbm2java
 */
@Entity
@Table(name = "detalles_pago", catalog = "scanappetite")
public class DetallesPago implements java.io.Serializable {

	private String numeroTarjeta;
	private int codigoSeguridad;
	private String fechaVencimiento;
	private String titularTarjeta;

	public DetallesPago() {
	}

	public DetallesPago(String numeroTarjeta, int codigoSeguridad) {
		this.numeroTarjeta = numeroTarjeta;
		this.codigoSeguridad = codigoSeguridad;
	}

	public DetallesPago(String numeroTarjeta, int codigoSeguridad, String fechaVencimiento, String titularTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
		this.codigoSeguridad = codigoSeguridad;
		this.fechaVencimiento = fechaVencimiento;
		this.titularTarjeta = titularTarjeta;
	}

	@Id

	@Column(name = "numero_tarjeta", unique = true, nullable = false)
	public String getNumeroTarjeta() {
		return this.numeroTarjeta;
	}

	public void setNumeroTarjeta(String numeroTarjeta) {
		this.numeroTarjeta = numeroTarjeta;
	}

	@Column(name = "codigo_seguridad", nullable = false)
	public int getCodigoSeguridad() {
		return this.codigoSeguridad;
	}

	public void setCodigoSeguridad(int codigoSeguridad) {
		this.codigoSeguridad = codigoSeguridad;
	}

	@Column(name = "fecha_vencimiento")
	public String getFechaVencimiento() {
		return this.fechaVencimiento;
	}

	public void setFechaVencimiento(String fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}

	@Column(name = "titular_tarjeta")
	public String getTitularTarjeta() {
		return this.titularTarjeta;
	}

	public void setTitularTarjeta(String titularTarjeta) {
		this.titularTarjeta = titularTarjeta;
	}

}
