package com.example.entitys;

import java.math.BigDecimal;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * DetallesPago generated by hbm2java
 */
@AllArgsConstructor
@NoArgsConstructor
@Builder
@ToString
@Getter
@Setter
@Entity
@Table(name = "detalles_pago", catalog = "scanappetite")
public class DetallesPago implements java.io.Serializable {

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mesa_id")
	private Mesa mesa;

	@Id
	@Column(name = "numero_tarjeta", unique = true, nullable = false)
	private String numeroTarjeta;

	@Column(name = "codigo_seguridad", nullable = false)
	private int codigoSeguridad;

	@Column(name = "fecha_vencimiento")
	private String fechaVencimiento;

	@Column(name = "titular_tarjeta")
	private String titularTarjeta;

	public DetallesPago(String numeroTarjeta, int codigoSeguridad, String fechaVencimiento, String titularTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
        this.codigoSeguridad = codigoSeguridad;
        this.fechaVencimiento = fechaVencimiento;
        this.titularTarjeta = titularTarjeta;
    }
}
