package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Mesa generated by hbm2java
 */
@Entity
@Table(name = "mesa", catalog = "scanappetite")
public class Mesa implements java.io.Serializable {

	
	
	private Long id;
	private Restaurante restaurante;
	private String ubicacion;
	private String estado;
	private List<Restaurante> restaurantes = new ArrayList<Restaurante>();
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
    private List<DetallesPago> detallesPago = new ArrayList<>();

	public Mesa() {
	}

	public Mesa(Long id, Restaurante restaurante) {
		this.id = id;
		this.restaurante = restaurante;
	}

	public Mesa(Long id, Restaurante restaurante, String ubicacion, String estado, List restaurantes) {
		this.id = id;
		this.restaurante = restaurante;
		this.ubicacion = ubicacion;
		this.estado = estado;
		this.restaurantes = restaurantes;
	
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RestauranteID", nullable = false)
	public Restaurante getRestaurante() {
		return this.restaurante;
	}

	public void setRestaurante(Restaurante restaurante) {
		this.restaurante = restaurante;
	}

	@Column(name = "Ubicacion")
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	@Column(name = "Estado")
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mesa")
	public List<Restaurante> getRestaurantes() {
		return this.restaurantes;
	}

	public void setRestaurantes(List restaurantes) {
		this.restaurantes = restaurantes;
	}

}
