package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PlatoPedido generated by hbm2java
 */
@Entity
@Table(name = "plato_pedido", catalog = "scanappetite")
public class PlatoPedido implements java.io.Serializable {

	private PlatoPedidoId id;
	private Pedido pedido;

	public PlatoPedido() {
	}

	public PlatoPedido(PlatoPedidoId id, Pedido pedido) {
		this.id = id;
		this.pedido = pedido;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "pedidoId", column = @Column(name = "pedido_id", nullable = false)),
			@AttributeOverride(name = "platoid", column = @Column(name = "platoid", nullable = false)) })
	public PlatoPedidoId getId() {
		return this.id;
	}

	public void setId(PlatoPedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedido_id", nullable = false, insertable = false, updatable = false)
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

}
