package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * PlatoPedidoId generated by hbm2java
 */
@Embeddable
public class PlatoPedidoId implements java.io.Serializable {

	private int pedidoId;
	private long platoid;

	public PlatoPedidoId() {
	}

	public PlatoPedidoId(int pedidoId, long platoid) {
		this.pedidoId = pedidoId;
		this.platoid = platoid;
	}

	@Column(name = "pedido_id", nullable = false)
	public int getPedidoId() {
		return this.pedidoId;
	}

	public void setPedidoId(int pedidoId) {
		this.pedidoId = pedidoId;
	}

	@Column(name = "platoid", nullable = false)
	public long getPlatoid() {
		return this.platoid;
	}

	public void setPlatoid(long platoid) {
		this.platoid = platoid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PlatoPedidoId))
			return false;
		PlatoPedidoId castOther = (PlatoPedidoId) other;

		return (this.getPedidoId() == castOther.getPedidoId()) && (this.getPlatoid() == castOther.getPlatoid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPedidoId();
		result = 37 * result + (int) this.getPlatoid();
		return result;
	}

}
