package com.example.entitys;
// Generated 18 dic 2023 20:02:34 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Restaurante generated by hbm2java
 */
@Entity
@Table(name = "restaurante", catalog = "scanappetite")
public class Restaurante implements java.io.Serializable {

	private String id;
	private Mesa mesa;
	private String direccion;
	
	
	private String denominacion;
	private String title;
	private Date horaApertura_1;
	private Date horaCierre_1;
	private List<Catalogo> catalogos = new ArrayList<Catalogo>();
	private List<Mesa> mesas = new ArrayList<Mesa>();

	public Restaurante() {
	}

	public Restaurante(String id) {
		this.id = id;
	}

	public Restaurante(String id, Mesa mesa, String direccion,  String denominacion,
			String title, Date horaApertura_1, Date horaCierre_1, List<Catalogo> catalogos, List<Mesa> mesas) {
		this.id = id;
		this.mesa = mesa;
		this.direccion = direccion;
	
		this.denominacion = denominacion;
		this.title = title;
		this.horaApertura_1 = horaApertura_1;
		this.horaCierre_1 = horaCierre_1;
		this.catalogos = catalogos;
		this.mesas = mesas;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MesaID")
	public Mesa getMesa() {
		return this.mesa;
	}

	public void setMesa(Mesa mesa) {
		this.mesa = mesa;
	}

	@Column(name = "Direccion")
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	

	

	@Column(name = "Denominacion", length = 120)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_apertura", length = 15)
	public Date getHoraApertura_1() {
		return this.horaApertura_1;
	}

	public void setHoraApertura_1(Date horaApertura_1) {
		this.horaApertura_1 = horaApertura_1;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "hora_cierre", length = 15)
	public Date getHoraCierre_1() {
		return this.horaCierre_1;
	}

	public void setHoraCierre_1(Date horaCierre_1) {
		this.horaCierre_1 = horaCierre_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurante")
	public List<Catalogo> getCatalogos() {
		return this.catalogos;
	}

	public void setCatalogos(List<Catalogo> catalogos) {
		this.catalogos = catalogos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "restaurante")
	public List<Mesa> getMesas() {
		return this.mesas;
	}

	public void setMesas(List<Mesa> mesas) {
		this.mesas = mesas;
	}

}
